assets:
  crypto:
    - BTC-USD
  stocks:
    - ^IXIC  # NASDAQ Index
  forex:
    - EURUSD=X
    - GBPUSD=X
    - GBPJPY=X
    - USDJPY=X
    - USDCAD=X
    - AUDCAD=X
  commodities:
    - XAUUSD=X  # Gold (Spot Price)
notification:
  discord:
    enabled: true
  logging:
    enabled: true
    level: INFO